### ISSUE TITLE
Path of bower_component is wrong

### ISSUE THREAD

**Issue by jaceju** [FabioAntunes/laravel-elixir-wiredep#1]
After wiredep, the template would be:

``` html
<!-- bower:css -->
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
<!-- endbower -->
```

But the full URL of `bootstrap.css` would be `http://homestead.app/auth/bower_components/bootstrap/dist/css/bootstrap.css` when I browse `http://homestead.app/auth/login`, it is wrong.

I found the pattern of `ignorePath` should be `/(\..\/)*public/`, not `/(\..\/)*public\//`, I fixed it in gulpfile.

Do I miss something?

**Comment by FabioAntunes** [comment]
I'm going to fix it, since this already happened to me, instead of injecting this:

``` html
<!-- bower:css -->
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
<!-- endbower -->
```

That is relative to actual path, from now on it will inject bower_components with the asset() helper function

``` php
<!-- bower:css -->
<link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.css') }}" />
<!-- endbower -->
```

**Comment by jaceju** [comment]
Thank you.
