### ISSUE TITLE
gulp --production

### ISSUE THREAD

**Issue by FDiskas** [FabioAntunes/laravel-elixir-wiredep#11]
Your script on production `gulp --production` should concat and minify the scripts and styles.
Nice plugin, but still useless in real world.

**Comment by FabioAntunes** [comment]
> This is a simple wrapper around Laravel Elixir for Wiredep.

Wiredep doesn't minify your scripts or your styles.

You can use this lib for that [https://www.npmjs.com/package/laravel-elixir-useref](laravel-elixir-useref)
