### ISSUE TITLE
It won't work with Laravel Elixir 3

### ISSUE THREAD

**Issue by jaceju** [FabioAntunes/laravel-elixir-wiredep#3]
Laravel Elixir 3 removed 'laravel-elixir/ingredients/commands/Utilities', but laravel-elixir-wiredep depends on it.

**Comment by walteranderson** [comment]
I'm having this issue as well. Just looked into what would need to change to update to Elixir 3.0 (details here https://github.com/laravel/elixir/releases/tag/3.0.0).

Using the new Task syntax is an easy fix but it's not as cut and dry as I had hoped. The function utilities.buildGulpSrc is no longer a part of Elixir 3. It kind of seems like GulpPaths.js has replaced that functionality, but it's not a simple replacement. I'll see if I can tinker with this some more and get a pull request in.

**Comment by EHLOVader** [comment]
@walteranderson, you can see how `GulpPaths` might be used in @JeffreyWay's [laravel-elixir-stylus](https://github.com/JeffreyWay/laravel-elixir-stylus/blob/master/index.js#L54)

I would also recommend branching to support 2.x Elixir and 3.x Elixir. To avoid problems with that I found the use of `peerDependencies` is helpful. You can see how I have done that in my [laravel-elixir-livereload](https://github.com/EHLOVader/laravel-elixir-livereload/blob/master/package.json#L33).

I rely on this package too, but haven't moved to Elixir 3.0 just yet. Too many packages haven't updated.

**Comment by killtw** [comment]
:+1:

**Comment by FabioAntunes** [comment]
Thanks for the report guys I will be checking the pull request this week and add support to elixir 3.

Sorry for the late reply, I was on vacation and without access to a computer.
