### ISSUE TITLE
ignorePath includes public but none of my paths have ever matched

### ISSUE THREAD

**Issue by EHLOVader** [FabioAntunes/laravel-elixir-wiredep#7]
Should the ignorePath on the default configuration be something more like `/(\..\/)*/` I don't see any instance where the public would match and have had to put ignorePath in explicitly in the past to accommodate.

**Comment by fabio-flubit** [comment]
Could you elaborate more? if I do change ignorePath to this `/(\..\/)*/` having a clean install of Laravel 5, creating the `.bowerrc` so you have your bower_components inside the public folder, then install jQuery with bower and save it on the bower.json and having the next `gulpfile.js`

```
var elixir = require('laravel-elixir');
var wiredep = require('laravel-elixir-wiredep');

elixir(function(mix) {
    mix.sass('app.scss').wiredep();
});
```

This is what gets injected into my `welcome.blade.php`:
```
<!-- bower:js -->
<script src="public/bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
```

When I want is clearly this:

```
<!-- bower:js -->
<script src="/bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
```

**Comment by FabioAntunes** [comment]
Could you elaborate more? if I do change ignorePath to this `/(\..\/)*/` having a clean install of Laravel 5, creating the `.bowerrc` so you have your bower_components inside the public folder, then install jQuery with bower and save it on the bower.json and having the next `gulpfile.js`

```
var elixir = require('laravel-elixir');
var wiredep = require('laravel-elixir-wiredep');

elixir(function(mix) {
    mix.sass('app.scss').wiredep();
});
```

This is what gets injected into my `welcome.blade.php`:

```
<!-- bower:js -->
<script src="public/bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
```

When I want is clearly this:

```
<!-- bower:js -->
<script src="/bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
```

**Comment by EHLOVader** [comment]
Ah, I had taken a different route with bower components and configured
nginx to point to its default location.

**Comment by FabioAntunes** [comment]
I'm leaving ignorePath as it is, this will give an out of box working solution. But thanks for the feedback, keep it coming.

**Comment by EHLOVader** [comment]
I might have a solution for both scenarios. Since it is a regexp, you could do this `/(\..\/)*(public)?/` but your
location for the components folder offers some complications I hadn't
experienced in finding a solution for #8

You will not want to ignore the public in the context of scss and less
files.

**Comment by FabioAntunes** [comment]
Commit 5ae9b0a1a66046292b04905d88856c7233269ffb solves your problem
